'''
Fixed Hyperparameters for each task

'''

mountain_car_params = {
    "action_map": {0: "left", 1: "none", 2: "right"},
    "max_steps": 200,
    "discount_factor": 1,
    "epsilon": 0,
    "min_eps": 0,
    "trace_decay": 0.99,
    "trace_scaling": None,
    "trace_accum": 0.2,
}

cartpole_params = {
    "action_map": {0: 'left', 1: 'right'},
    "max_steps": 300,
    "discount_factor": 0.99,
    "epsilon": 1,
    "min_eps": 0,
    "trace_decay": 0.9,
    "trace_scaling": None,
    "trace_accum": 0.2,
}

lunar_params = {
    "action_map": {0: 'none', 1: 'left engine', 2: 'main engine', 3: 'right engine'},
    "max_steps": 1000,
    "discount_factor": 0.99,
    "epsilon": 0,
    "min_eps": 0,
    "trace_decay": 0.9,
    "trace_scaling": 1,
    "trace_accum": 0.2,
}

taxi_params = {
    "action_map": {0: 'South', 1: 'North', 2: 'East', 3: 'West', 4: 'Pickup', 5: 'Drop off'},
    "max_steps": 200,
    "discount_factor": 0.99,
    "epsilon": 1,
    "min_eps": 0,
    "trace_decay": 0.9,
    "trace_scaling": 1,
    "trace_accum": 0.2,
}

HYPERPARAMS = {
    "MountainCar-v0": mountain_car_params,
    "CartPole-v1": cartpole_params,
    "LunarLander-v3": lunar_params,
    "Taxi-v3": taxi_params,
}

#####################################################
#### PREFERENCE TRAJECTORY INFORMATION ##############
####   Generated by user preferences in APReL    ####
#####################################################
PREF_WEIGHTS = {
    "MountainCar-v0": {"user_weights":[-0.28493522,  0.72942661,  0.62189126], 
                       "mean": [-0.703, -0.344, 0.007],
                       "std": [0.075, 0.074, 0.003]
                       },
    "CartPole-v1": {"user_weights":[-0.61644258, -0.21192496, 0.37364577, 0.34315363, -0.43328074,-0.3605393],
                    "mean":[0.08042376, 0.22454314, 0.05853156, 0.14392722, 0.71425855, 0.440465],
                    "std": [0.01982235, 0.01125918, 0.03071498, 0.08191463, 0.22786573, 0.1700408]
                   },
    "LunarLander-v3": {"user_weights":[-0.34338366, -0.52104169, -0.08826276, -0.53844131, -0.42664324,-0.36175877],
                       "mean":[1.01697632, 0.29293008, 0.93917414, 0.45834444, 0.85476801, 0.03478659],
                       "std":[0.15846024, 0.21725001, 0.19274371, 0.30549547, 0.59639926, 0.01980674]
                      },
}

